---

  - name: set timezone
    template: src=timezone.j2 dest=/etc/timezone
    tags: [timezone]

  - name: set localtime
    file:
      src: /usr/share/zoneinfo/{{ timezone }}
      dest: /etc/localtime
      state: link
      owner: root
      group: root
      mode: 0644
      force: yes
    #  - update tzdata
    tags: [timezone]

# Disable unwanted services
  - name: Disable selinux
    selinux: state=disabled

  - name: Disable chargen-dgram (check if exists)
    stat: path=/etc/xinetd.d/chargen-dgram
    register: chargen_dgram
    tags: check chargen dgram

  - name: Disable chargen-dgram (disable xinetd service)
    service: name=chargen-dgram state=stopped enabled=no
    when: chargen_dgram.stat.exists
    tags: disable chargen dgram

  - name: Disable chargen-stream (check if exists)
    stat: path=/etc/xinetd.d/chargen-stream
    register: chargen_stream
    tags: check chargen stream

  - name: Disable chargen-stream (disable xinetd service)
    service: name=chargen-stream state=stopped enabled=no
    when: chargen_stream.stat.exists
    tags: disable chargen stream

  - name: Disable daytime-dgram (check if exists)
    stat: path=/etc/xinetd.d/daytime-dgram
    register: daytime_dgram
    tags: check daytime dgram

  - name: Disable daytime-dgram (disable xinetd service)
    service: name=daytime-dgram tate=stopped enabled=no
    when: daytime_dgram.stat.exists
    tags: disable daytime dgram

  - name: Disable daytime-stream (check if exists)
    stat: path=/etc/xinetd.d/daytime-stream
    register: daytime_stream
    tags: check daytime stream

  - name: Disable daytime-stream (disable xinetd service)
    service: name=daytime-stream state=stopped enabled=no
    when: daytime_stream.stat.exists
    tags: disable xinetd daytime stream

  - name: Disable echo-dgram (check if exists)
    stat: path=/etc/xinetd.d/echo-dgram
    register: echo_dgram
    tags: check echo dgram

  - name: Disable echo-dgram (disable xinetd service)
    service: name=echo-dgram state=stopped enabled=no
    when: echo_dgram.stat.exists
    tags: disable xinted echo stream

  - name: Disable echo-stream (check if exists)
    stat: path=/etc/xinetd.d/echo-stream
    register: echo_stream
    tags: check echo stream

  - name: Disable echo-stream (disable xinetd service)
    service: name=echo-stream state=stopped enabled=no
    when: echo_stream.stat.exists
    tags: disable echo stream

  - name: Disable tcpmux-server (check if exists)
    stat: path=/etc/xinetd.d/tcpmux-server
    register: tcpmux_server
    tags: check tcpmux server

  - name: Disable tcpmux-server (disable xinetd service)
    service: name=tcpmux-server state=stopped enabled=no
    when: tcpmux_server.stat.exists
    tags: disable tcmux server

  - name: Remove X Windows (runlevel 3)
    lineinfile: >
      dest=/etc/inittab
      state=present
      regexp="^id:"
      line="id:3:initdefault:"
    tags: remove xwindows init3

  - name: Disable Avahi Server (check if installed)
    stat: path=/etc/init.d/avahi-daemon
    register: avahi_service
    tags: avahi

  - name: Disable Avahi Server (disable service)
    service: name=avahi-daemon state=stopped enabled=no
    when: avahi_service.stat.exists
    tags: avahi

  - name: Check to see if cups daemon is installed
    stat: path=/etc/init.d/cups
    register: cups_service
    tags: cups

  - name: Disable Print Server - CUPS
    service: name=cups state=stopped enabled=no
    ignore_errors: yes
    when: cups_service.stat.exists
    tags: cups

  - name: NFS and RPC (check for nfs-utils)
    stat: path=/etc/init.d/nfslock
    register: nfs_utils
    tags: nfs

  - name: Disable NFS and RPC (check for rpcbind)
    stat: path=/etc/init.d/rpcbind
    register: rpcbind
    tags: nfs

  - name: Disable NFS and RPC (nfs-utils services)
    service: >
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
    - nfslock
    - rpcgssd
    - rpcidmapd
    - rpcsvcgssd
    when: nfs_utils.stat.exists
    tags: nfs

  - name: Disable NFS and RPC (rpcbind services)
    service: >
      name=rpcbind
      state=stopped
      enabled=no
    when:
    - rpcbind.stat.exists
    tags: nfs

  - name: Configure Mail Transfer Agent for Local-Only Mode
    lineinfile: >
      backup=yes
      state=present
      dest=/etc/postfix/main.cf
      backrefs=yes
      regexp="^inet_interfaces"
      line="inet_interfaces = localhost"
    ignore_errors: yes
    tags: postfix

  - name: Disable IP Forwarding
    sysctl: >
      name=net.ipv4.ip_forward
      value=0
      state=present
    tags: ipv4 forward

  - name: Disable Send Packet Redirects
    sysctl: >
      name=net.ipv4.conf.all.send_redirects
      value=0
      state=present
      ignoreerrors=true
    tags: send packet redirects

  - name: Disable Send Packet Redirects
    sysctl: >
      name=net.ipv4.conf.default.send_redirects
      value=0
      state=present
      ignoreerrors=true
    tags: send packet redirects

  - name: Disable Source Routed Packet Acceptance
    sysctl: >
      name=net.ipv4.conf.all.accept_source_route
      value=0
      state=present
      ignoreerrors=true
    tags: source routed packets

  - name: Disable Source Routed Packet Acceptance
    sysctl: >
      name=net.ipv4.conf.default.accept_source_route
      value=0
      state=present
      ignoreerrors=true
    tags: source routed packets

  - name: Disable ICMP Redirect Acceptance
    sysctl: >
      name=net.ipv4.conf.all.accept_redirects
      value=0
      state=present
      ignoreerrors=true
    tags: icmp redirect acceptance

  - name: Disable ICMP Redirect Acceptance
    sysctl: >
      name=net.ipv4.conf.default.accept_redirects
      value=0
      state=present
      ignoreerrors=true
    tags: icmp redirect acceptance

  - name: Log Suspicious Packets
    sysctl: >
      name=net.ipv4.conf.all.log_martians
      value=1
      state=present
      ignoreerrors=true
    tags: log suspicious packets

  - name: Log Suspicious Packets
    sysctl: >
      name=net.ipv4.conf.default.log_martians
      value=1
      state=present
      ignoreerrors=true
    tags: log suspicious packets

  - name: Enable Ignore Broadcast Requests
    sysctl: >
      name=net.ipv4.icmp_echo_ignore_broadcasts
      value=1
      state=present
      ignoreerrors=true
    tags: ignore broadcast requests

  - name: Enable Bad Error Message Protection
    sysctl: >
      name=net.ipv4.icmp_ignore_bogus_error_responses
      value=1
      state=present
      ignoreerrors=true
    tags: bad error message protection

  - name: Enable TCP SYN Cookies
    sysctl: >
      name=net.ipv4.tcp_syncookies
      value=1
      state=present
      ignoreerrors=true
    tags: tcp syn cookies

  - name: Disable Secure ICMP Redirect Acceptance
    sysctl: >
      name=net.ipv4.conf.all.secure_redirects
      value=0
      state=present
      ignoreerrors=true
    tags: icmp redirect acceptance

  - name: Disable Secure ICMP Redirect Acceptance
    sysctl: >
      name=net.ipv4.conf.default.secure_redirects
      value=0
      state=present
      ignoreerrors=true
    tags: icmp redirect acceptance

  - name: Enable RFC-recommended Source Route Validation
    sysctl: >
      name=net.ipv4.conf.all.rp_filter
      value=1
      state=present
      ignoreerrors=true
    tags:
    - source route validation

  - name: Enable RFC-recommended Source Route Validation
    sysctl: >
      name=net.ipv4.conf.default.rp_filter
      value=1
      state=present
      ignoreerrors=true
    tags:
    - source route validation

  - name: Set SSH Protocol to 2
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^Protocol " line="Protocol 2"
    notify: Reload sshd
    tags:
    - SSHv2

  - name: Set LogLevel to INFO
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^LogLevel "
      line="LogLevel INFO"
    notify: Reload sshd
    tags:
    - loglevel info SSHD

  - name: Set Permissions on /etc/ssh/sshd_config
    file: >
      path=/etc/ssh/sshd_config
      owner=root
      group=root
      mode=0600
    notify: Reload sshd
    tags:
    - sshd_config perms

  - name: Disable SSH X11 Forwarding
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^X11Forwarding "
      line="X11Forwarding no"
    notify: Reload sshd
    tags:
    - disable X11 forwarding

  - name: Set SSH MaxAuthTries to 5 or Less
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^MaxAuthTries "
      line="MaxAuthTries 5"
    notify: Reload sshd
    tags:
    - sshd max tries 5

  - name: Set SSH IgnoreRhosts to Yes
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^IgnoreRhosts "
      line="IgnoreRhosts yes"
    notify: Reload sshd
    tags:
    - ignore rhosts

  - name: Set SSH HostbasedAuthentication to No
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^HostbasedAuthentication "
      line="HostbasedAuthentication no"
    notify: Reload sshd
    tags:
    - disable host base auth

  - name: Disable SSH Root Login
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitRootLogin "
      line="PermitRootLogin no"
    notify: Reload sshd
    tags:
    - disable root ssh

  - name: Set SSH PermitEmptyPasswords to No
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitEmptyPasswords "
      line="PermitEmptyPasswords no"
    notify: Reload sshd
    tags:
    - disable empty passwords

  - name: Do Not Allow Users to Set Environment Options
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitUserEnvironment "
      line="PermitUserEnvironment no"
    notify: Reload sshd
    tags:
    - disable user env

  - name: Use Only Approved Cipher in Counter Mode
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^Ciphers "
      line="Ciphers aes128-ctr,aes192-ctr,aes256-ctr"
    notify: Reload sshd
    tags:
     - secure SSH ciphers

  - name: Set Idle Timeout Interval for User Login
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^ClientAliveInterval "
      line="ClientAliveInterval 300"
    notify: Reload sshd
    tags:
    - idle timeout

  - name: Set Idle Timeout Interval for User Login
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^ClientAliveCountMax "
      line="ClientAliveCountMax 0"
    notify: Reload sshd
    tags:
    - idle timeout interval

  - name: Set SSH Banner
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^Banner "
      line="Banner /etc/issue.net"
    notify: Reload sshd
    tags:
    - issue.net banner

  - name: Set Warning Banner for Standard Login Services
    stat: path=/etc/{{ item }}
    register: stats
    with_items:
      - motd
      - issue
      - issue.net
    tags:
    - banners

  - name: Set Warning Banner for Standard Login Services
    file: >
      name=/etc/motd
      state=absent
    changed_when: false
    with_items:
      - stats.results
    when: item.islnk is defined
    tags:
    - motd

  - name: Set Warning Banner for Standard Login Services
    file: >
      name=/etc/issue
      state=absent
    changed_when: false
    with_items:
      - stats.results
    when: item.islnk is defined
    tags:
    - issue

  - name: Set Warning Banner for Standard Login Services
    file: >
      name=/etc/issue.net
      state=absent
    changed_when: false
    with_items:
      - stats.results
    when: item.islnk is defined
    tags: issue.net

  - name: Set Warning Banner for Standard Login Services
    template: src={{item}} dest=/etc/{{item}}
    with_items:
      - motd
      - issue
      - issue.net
    tags: motd issue issue.net

  - name: Set Warning Banner for Standard Login Services
    file: >
      path=/etc/{{ item }}
      owner=root
      group=root
      mode=0644
    with_items:
      - motd
      - issue
      - issue.net
    tags: motd issue issue.net

  - name: Remove OS Information from Login Warning Banners
    replace: >
      dest=/etc/{{ item }}
      regexp='\\r|\\v|\\s'
      replace='[TracFone]'
    with_items:
      - motd
      - issue
      - issue.net
    tags: Remove OS info from banners

# Pushing REPOS (temp) manually to boxes for anisble
#  - name: Install EPEL6_x64 repo
#    action: command rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

# Pushing REPOS (temp) manually to boxes for anisble
#  - name: Install IUS6_x64 repo
#    action: command rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/ius-release-1.0-13.ius.el6.noarch.rpm